spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost

server:
  port: 8080

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082

payment-service:
  host: localhost
  port: 9080

dicebear:
  baseUrl: https://api.dicebear.com/9.x/
  styleNames:
    - adventurer
    - avataaars
    - big-ears
    - big-smile
    - bottts
    - dylan
    - micah
    - miniavs
    - open-peeps
    - personas
  seeds:
    - emery
    - jameson
    - kimberly
    - aidan
    - brooklynn
    - destiny
    - jessica
    - maria
    - ryker
    - amaya
    - eliza
    - aiden
    - luis
    - liam
    - valentina
    - vivian
    - caleb
    - chase
    - sadie
    - katherine