spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      connect_timeout: 5000
      read_timeout: 3000

server:
  port: 8080

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082

payment-service:
  host: localhost
  port: 9080

#s3 config
services:
  s3:
    endpoint: http://192.168.1.111:9000
    accessKey: user
    secretKey: password
    bucketName: corpbucket

#Avatar config
avatar:
  max-size-bytes: 5242880    # 5MB (макс. размер файла)
  folder-template: "users/{username}/avatars"
  sizes:
    large: 1080
    small: 170

# Premium remover config
premium-remover:
  executor:
    core-size: 3
    max-size: 9
    queue-capacity: 75
    thread-name-prefix: "premium-remover-"
  scheduled:
    cron: "0 0 6 * * ?"
    batch-size: 100