spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_IP:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: localhost
    port: 6379

  kafka:
    bootstrap-servers: localhost:9092

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost

server:
  port: 8080

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082

payment-service:
  host: localhost
  port: 9080

management:
  endpoints:
    web:
      exposure:
        include: caches

domain:
  path: /api/v1

redis:
  ttl-minutes: 2

minio:
  accessKey: user
  secretKey: password
  endpoint: http://localhost:9000

avatar:
  bucket: avatars
  default-avatar: default-avatar.png
  size: 64
  small-size: 32

dicebear:
  endpoint: https://api.dicebear.com

user:
  ban:
    redis:
      channel: user_ban

service:
  name: user-service

premium:
  scheduler:
    remove-cron: "0 0 * * * 1"  # every monday in 00:00
    batch: 5

kafka:
  goal:
    completed:
      topic: goal_completed_topic