spring:
  datasource:
    url: jdbc:postgresql://localhost:9999/fake
    username: fakeuser
    password: fakepass
  jpa:
    hibernate:
      ddl-auto: update
  test:
    database:
      replace: none

server:
  port: 8080
